version: '3.8'

services:
  db:
    image: postgres:11
    env_file:
      - .env
    ports:
      - "5432:5432"
  back:
    build:
      context: .
    command: gunicorn --worker-tmp-dir=/dev/shm --workers=2 --threads=4 --worker-class=gthread --log-file=- --bind=0.0.0.0:8000 the_eye.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A the_eye worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - back
